# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f704860a9a35aca85e81457e7c27471d2376b3fc23a0cc5a320202823db4fcc878adf2f70f6eb0be0a42fa554a7ae6a07f31eaf67423778496c2d41f593b001

test:
  secret_key_base: aac1f61561e30ea5a5dcc328f57ccc5a9d274c1368f914534210b782fc8a4d3f90635efaa2f3328042b54fae96610e81c3e472ad761bc8f537330c11c6bdf298

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
